# Generated by Django 5.1.6 on 2025-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='delivery_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cans_delivered', models.PositiveIntegerField(default=0)),
                ('cans_received_empty', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
