# Generated by Django 5.1.6 on 2025-05-28 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Delivery', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryproof',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.dailydeliverylog'),
        ),
    ]
