# Generated by Django 5.1.6 on 2025-05-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_initial'),
        ('customerlog', '0002_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryproof',
            name='delivery',
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='bulk_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerlog.bulkorder'),
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='daily_delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.dailydeliverylog'),
        ),
    ]
