# Generated by Django 5.1.6 on 2025-05-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_remove_deliveryproof_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryproof',
            name='photo',
        ),
    ]
