# Generated by Django 5.1.6 on 2025-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('confirmed_by_delivery_boy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_day', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HelpChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
