# Generated by Django 5.1.6 on 2025-05-28 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerlog', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.customerprofile'),
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner.deliveryboyprofile'),
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='water_can',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner.watercan'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.customerprofile'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner.deliveryboyprofile'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='water_can',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner.watercan'),
        ),
        migrations.AddField(
            model_name='helpchatlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.customerprofile'),
        ),
    ]
